name: Build & Publish Docker Image
on:
  release:
    types: [published]

jobs:
  push-to-ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          scopes: write:packages
      - name: Extract Metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Debug Metadata Tags
        run: |
          echo "Metadata Tags: ${{ steps.metadata.outputs.tags }}"
      - name: Build & Publish Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # tags: ${{ steps.metadata.outputs.tags }}
          tags: latest
          labels: ${{ steps.metadata.outputs.labels }}
        
        