name: Build and Publish Docker Image
on:
    release: 
        types: [published]
jobs:
    push-to-ghcr:
        runs-on: ubuntu-latest
        permissions: 
            packages: write
            contents: read
        steps:
            - name: Login to GHCR
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.action }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract Metadata
              id: metadata
              uses: docker/metadata-actions@v4
              with:
                images: |
                  ghcr.io/${{ github.repository }}
                tags: |
                  type: semver,pattern={{version}}
                  type: semver,pattern={{major}}.{{minor}}
            - name: Build and Publish Docker Image
              uses: docker/build-push-action@v4
              with:
                Context: .
                file: ./Dockerfile
                push: true
                tags: ${{ steps.metadata.outputs.tags }}
                labels: ${{ steps.metadata.outputs.labels }}
